// <auto-generated />
using System;
using Exame.Infrastructure.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Exame.Infrastructure.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20260625215300_AddSpListaMovimentos")]
    partial class AddSpListaMovimentos
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.9")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Exame.Domain.Entities.MovimentoManual", b =>
                {
                    b.Property<decimal>("DatMes")
                        .HasColumnType("numeric(2,0)")
                        .HasColumnName("DAT_MES");

                    b.Property<decimal>("DatAno")
                        .HasColumnType("numeric(4,0)")
                        .HasColumnName("DAT_ANO");

                    b.Property<decimal>("NumLancamento")
                        .HasColumnType("numeric(18,0)")
                        .HasColumnName("NUM_LANCAMENTO");

                    b.Property<string>("IdProduto")
                        .HasColumnType("char(4)")
                        .HasColumnName("ID_PRODUTO");

                    b.Property<string>("IdCosif")
                        .HasColumnType("varchar(11)")
                        .HasColumnName("ID_COSIF");

                    b.Property<DateTime>("DatMovimento")
                        .HasColumnType("smalldatetime")
                        .HasColumnName("DAT_MOVIMENTO");

                    b.Property<string>("DesDescricao")
                        .IsRequired()
                        .HasColumnType("varchar(50)")
                        .HasColumnName("DES_DESCRICAO");

                    b.Property<string>("IdUsuario")
                        .IsRequired()
                        .HasColumnType("varchar(15)")
                        .HasColumnName("ID_USUARIO");

                    b.Property<decimal>("ValValor")
                        .HasColumnType("numeric(18,2)")
                        .HasColumnName("VAL_VALOR");

                    b.HasKey("DatMes", "DatAno", "NumLancamento", "IdProduto", "IdCosif");

                    b.HasIndex("IdProduto", "IdCosif");

                    b.ToTable("MOVIMENTO_MANUAL", (string)null);
                });

            modelBuilder.Entity("Exame.Domain.Entities.Produto", b =>
                {
                    b.Property<string>("IdProduto")
                        .HasColumnType("char(4)")
                        .HasColumnName("ID_PRODUTO");

                    b.Property<string>("DesProduto")
                        .HasColumnType("varchar(30)")
                        .HasColumnName("DES_PRODUTO");

                    b.Property<string>("StaStatus")
                        .HasColumnType("char(1)")
                        .HasColumnName("STA_STATUS");

                    b.HasKey("IdProduto");

                    b.ToTable("PRODUTO", (string)null);
                });

            modelBuilder.Entity("Exame.Domain.Entities.ProdutoCosif", b =>
                {
                    b.Property<string>("IdProduto")
                        .HasColumnType("char(4)")
                        .HasColumnName("ID_PRODUTO");

                    b.Property<string>("IdCosif")
                        .HasColumnType("varchar(11)")
                        .HasColumnName("ID_COSIF");

                    b.Property<string>("IdClassificacao")
                        .HasColumnType("char(6)")
                        .HasColumnName("ID_CLASSIFICACAO");

                    b.Property<string>("StaStatus")
                        .HasColumnType("char(1)")
                        .HasColumnName("STA_STATUS");

                    b.HasKey("IdProduto", "IdCosif");

                    b.ToTable("PRODUTO_COSIF", (string)null);
                });

            modelBuilder.Entity("Exame.Domain.Entities.MovimentoManual", b =>
                {
                    b.HasOne("Exame.Domain.Entities.ProdutoCosif", "ProdutoCosif")
                        .WithMany("MovimentosManuais")
                        .HasForeignKey("IdProduto", "IdCosif")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("ProdutoCosif");
                });

            modelBuilder.Entity("Exame.Domain.Entities.ProdutoCosif", b =>
                {
                    b.HasOne("Exame.Domain.Entities.Produto", "Produto")
                        .WithMany("ProdutoCosifs")
                        .HasForeignKey("IdProduto")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Produto");
                });

            modelBuilder.Entity("Exame.Domain.Entities.Produto", b =>
                {
                    b.Navigation("ProdutoCosifs");
                });

            modelBuilder.Entity("Exame.Domain.Entities.ProdutoCosif", b =>
                {
                    b.Navigation("MovimentosManuais");
                });
#pragma warning restore 612, 618
        }
    }
}
